-- Create monthly P/L table
CREATE TABLE IF NOT EXISTS monthly_pl (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    month DATE NOT NULL, -- Store as first day of month for easy querying
    configuration_id BIGINT REFERENCES trade_configurations(id),
    regular_trades_pl DECIMAL(15,2) NOT NULL DEFAULT 0,
    strategy_trades_pl DECIMAL(15,2) NOT NULL DEFAULT 0,
    total_pl DECIMAL(15,2) GENERATED ALWAYS AS (regular_trades_pl + strategy_trades_pl) STORED,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    UNIQUE(month, configuration_id)
);

-- Add RLS policies
ALTER TABLE monthly_pl ENABLE ROW LEVEL SECURITY;

-- Allow read access to authenticated users
CREATE POLICY "Allow read access for authenticated users" ON monthly_pl
    FOR SELECT
    TO authenticated
    USING (true);

-- Allow insert/update access to service role only
CREATE POLICY "Allow insert/update for service role" ON monthly_pl
    FOR ALL
    TO service_role
    USING (true)
    WITH CHECK (true);

-- Create function to update updated_at timestamp
CREATE OR REPLACE FUNCTION update_monthly_pl_updated_at()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Create trigger to automatically update updated_at
CREATE TRIGGER update_monthly_pl_updated_at
    BEFORE UPDATE ON monthly_pl
    FOR EACH ROW
    EXECUTE FUNCTION update_monthly_pl_updated_at();

-- Create index for faster querying
CREATE INDEX idx_monthly_pl_month ON monthly_pl(month);
CREATE INDEX idx_monthly_pl_config ON monthly_pl(configuration_id);

-- Add comment to table
COMMENT ON TABLE monthly_pl IS 'Stores monthly profit/loss data for each trade configuration';

-- Add comments to columns
COMMENT ON COLUMN monthly_pl.id IS 'Unique identifier for the monthly P/L record';
COMMENT ON COLUMN monthly_pl.month IS 'First day of the month for this P/L record';
COMMENT ON COLUMN monthly_pl.configuration_id IS 'Reference to the trade configuration';
COMMENT ON COLUMN monthly_pl.regular_trades_pl IS 'Total P/L from regular trades for this month and configuration';
COMMENT ON COLUMN monthly_pl.strategy_trades_pl IS 'Total P/L from strategy trades for this month and configuration';
COMMENT ON COLUMN monthly_pl.total_pl IS 'Computed total P/L (regular + strategy)';
COMMENT ON COLUMN monthly_pl.created_at IS 'Timestamp when the record was created';
COMMENT ON COLUMN monthly_pl.updated_at IS 'Timestamp when the record was last updated'; 