"""Update database for some changes

Revision ID: 7ea347927615
Revises: 76c6b1051796
Create Date: 2024-10-09 14:53:27.474045

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy import text, inspect


# revision identifiers, used by Alembic.
revision: str = '7ea347927615'
down_revision: Union[str, None] = '76c6b1051796'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Import the necessary SQLAlchemy types
    from sqlalchemy.engine.reflection import Inspector
    from sqlalchemy import inspect

    # Get the SQLAlchemy connection
    conn = op.get_bind()
    inspector = inspect(conn)
    
    # Check if the temporary table exists and drop it if it does
    conn.execute(text("DROP TABLE IF EXISTS _alembic_tmp_trades"))

    # Get existing column names
    existing_columns = [col['name'] for col in inspector.get_columns('trades')]

    # Check and add 'average_price' if it doesn't exist
    if 'average_price' not in existing_columns:
        op.add_column('trades', sa.Column('average_price', sa.Float(), nullable=True, server_default=text('-1.0')))
    
    # Check and add 'size' if it doesn't exist
    if 'size' not in existing_columns:
        op.add_column('trades', sa.Column('size', sa.String(), nullable=False, server_default=text("''")))

    # Check and add 'average_exit_price' if it doesn't exist
    if 'average_exit_price' not in existing_columns:
        op.add_column('trades', sa.Column('average_exit_price', sa.Float(), nullable=True, server_default=text('-1.0')))

    # Workaround for altering 'current_size' column to be nullable
    with op.batch_alter_table('trades', recreate='always') as batch_op:
        batch_op.alter_column('current_size', 
                              existing_type=sa.Float(), 
                              nullable=True)

    # Add any other operations from your original migration here
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('trades', 'current_size',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('trades', 'average_exit_price')
    op.drop_column('trades', 'size')
    op.drop_column('trades', 'average_price')
    # ### end Alembic commands ###
